name: flutter_todo_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  get: 4.6.6
  get_storage: ^2.1.1
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
